version: '2.1'
services:
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/mydata.conf:/etc/nginx/conf.d/mydata.conf
      - ./_front:/usr/share/nginx/mydata
  python:
    build: ./docker/python
    volumes:
      - ./_back:/usr/src/app/cgi-bin
  db:
    build: ./docker/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - ./docker/mariadb/init.sql:/tmp/init.sql
